version: 2
project_name: terraform-provider-popsrox-utils
release:
  github:
    owner: POps-Rox
    name: terraform-provider-popsrox-utils
  draft: false
  name_template: '{{.Tag}}'
builds:
- id: terraform-provider-popsrox-utils
  goos:
  - freebsd
  - openbsd
  - solaris
  - windows
  - linux
  - darwin
  goarch:
  - amd64
  - "386"
  - arm
  - arm64
  goarm:
  - "6"
  targets:
  - freebsd_amd64
  - freebsd_386
  - freebsd_arm_6
  - freebsd_arm64
  - openbsd_amd64
  - openbsd_386
  - solaris_amd64
  - windows_amd64
  - windows_386
  - linux_amd64
  - linux_386
  - linux_arm_6
  - linux_arm64
  - darwin_amd64
  - darwin_arm64
  ignore:
  - goos: darwin
    goarch: "386"
    goarm: ""
    gomips: ""
  - goos: openbsd
    goarch: arm
    goarm: ""
    gomips: ""
  - goos: openbsd
    goarch: arm64
    goarm: ""
    gomips: ""
  dir: .
  main: .
  ldflags:
  - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser
  binary: '{{ .ProjectName }}_v{{ .Version }}'
  env:
  - CGO_ENABLED=0
archives:
- id: default
  ids:
  - terraform-provider-popsrox-utils
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  formats:
  - zip
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
snapshot:
  version_template: '{{ .Tag }}-SNAPSHOT-{{ .ShortCommit }}'
signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--yes"
      - "--passphrase-fd"
      - "0"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
    stdin: "{{ .Env.GPG_PASSPHRASE }}"
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
changelog:
  disable: true
before:
  hooks:
  - go mod tidy
source:
  name_template: '{{ .ProjectName }}-{{ .Version }}'
  format: tar.gz
github_urls:
  download: https://github.com
gitlab_urls:
  download: https://gitlab.com
