site_name: "Azure NoOps Utils Provider"
site_description: Documentation for Azure NoOps Utils Provider
repo_url: https://github.com/POps-Rox/tf-provider-azutils
edit_uri: edit/main/docs/

nav:
  - Home: index.md

plugins:
  - techdocs-core

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
